
package inventario;

import BaseDatos.ConexionDatosdeReporte;
import BaseDatos.ConexionEmpresas;
import Reportes.GenerarExceF4;
import Reportes.GenerarExistGeneral;
import Reportes.ReporteF157;

import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class Reportes extends javax.swing.JDialog {
ConexionEmpresas secciones=new ConexionEmpresas();
  int mes_reporte;
  int anio_reporte;
  int seccion;
    public Reportes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        secciones.consulta();
        seccion=secciones.codigo_empresa();
        Progreso.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Etiq_encabezado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Panel_Layout = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        Panel_barra = new javax.swing.JPanel();
        Progreso = new javax.swing.JProgressBar();
        Panel_general = new javax.swing.JPanel();
        boton_kardex = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        panel1 = new javax.swing.JPanel();
        Combo_Meses = new javax.swing.JComboBox();
        Campo_Anio = new javax.swing.JTextField();
        Boton_f157 = new javax.swing.JButton();
        Boton_Modelo4 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Etiq_encabezado.setText("<html><body><br><center>Sistema Administrativo de Inventario <br>HOSPITAL DR. SAMUEL DARIO MALDONADO</body></html>");

        jLabel1.setText("Reportes");

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Panel_Layout.add(jButton1);

        Progreso.setForeground(new java.awt.Color(0, 0, 204));
        Panel_barra.add(Progreso);

        boton_kardex.setText("Kardex");
        boton_kardex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_kardexActionPerformed(evt);
            }
        });
        Panel_general.add(boton_kardex);

        jSeparator2.setBorder(javax.swing.BorderFactory.createTitledBorder("Rango de fecha"));

        Combo_Meses.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ENERO", "FEBRERO", "MARZO", "ABRIL", "MAYO", "JUNIO", "JULIO", "AGOSTO", "SEPTIEMBRE", "OCTUBRE", "NOVIEMBRE", "DICIEMBRE" }));

        Campo_Anio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                Campo_AnioFocusLost(evt);
            }
        });
        Campo_Anio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Campo_AnioKeyTyped(evt);
            }
        });

        Boton_f157.setText("F-15-7");
        Boton_f157.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_f157ActionPerformed(evt);
            }
        });

        Boton_Modelo4.setText("Modelo 4");
        Boton_Modelo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_Modelo4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Combo_Meses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Boton_Modelo4))
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Boton_f157)
                    .addComponent(Campo_Anio, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Combo_Meses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Campo_Anio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Boton_f157)
                    .addComponent(Boton_Modelo4))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jSeparator3.setBorder(javax.swing.BorderFactory.createTitledBorder("Informacion Completa"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Etiq_encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Panel_Layout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Panel_general, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Panel_barra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2)
                            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator3))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Etiq_encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Panel_general, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Panel_barra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Panel_Layout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int opcion= JOptionPane.showConfirmDialog(null," ¿Seguro desea Salir?. ¡No se conservara nada que no haya guardado!", "Confirmacion de Cancelar", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        //opcion 0= Si, 1=No
         if (opcion==0)
         {
             this.dispose();
         }//if
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Boton_Modelo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_Modelo4ActionPerformed
        if(Campo_Anio.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Debe indicar el año", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
        anio_reporte=Integer.parseInt(Campo_Anio.getText());
       
        switch(Combo_Meses.getSelectedIndex())
        {
            case 0:mes_reporte=1;
                break;
            case 1:mes_reporte=2;
                break;
            case 2:mes_reporte=3;
                break;
            case 3:mes_reporte=4;
                break;
            case 4:mes_reporte=5;
                break;
            case 5:mes_reporte=6;
                break;
            case 6:mes_reporte=7;
                break;
            case 7:mes_reporte=8;
                break;
            case 8:mes_reporte=9;
                break;
            case 9:mes_reporte=10;
                break;
            case 10:mes_reporte=11;
                break;
            case 11:mes_reporte=12;
                break;
               
                
        }
        
       
        GenerarExceF4 progress=new GenerarExceF4();
        Progreso.setVisible(true);
        progress.setFechaReporte(mes_reporte, anio_reporte);
        progress.setProgreso(Progreso);//paso la barra como parametro a la ventana de SwingWorker para que la actualice
        progress.setSeccion(seccion);
        progress.execute();
    
        }//else
    }//GEN-LAST:event_Boton_Modelo4ActionPerformed

    private void Campo_AnioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Campo_AnioKeyTyped
        // TODO add your handling code here:
        char caracter=evt.getKeyChar();
         if(((caracter < '0') || (caracter > '9')) && (caracter != '\b' /*corresponde a BACK_SPACE*/) && (caracter !='.'))
      {
         JOptionPane.showMessageDialog(null, "Este campo solo se admiten numeros", "Revisar", JOptionPane.ERROR_MESSAGE);
         evt.consume();
      }
       
    }//GEN-LAST:event_Campo_AnioKeyTyped

    private void Campo_AnioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Campo_AnioFocusLost
        // TODO add your handling code here:
         if(Campo_Anio.getText().length()< 4)
            {
               JOptionPane.showMessageDialog(null, "Este campo debe tener 4 digitos", "Revisar", JOptionPane.ERROR_MESSAGE);
              
            }//if
    }//GEN-LAST:event_Campo_AnioFocusLost

    private void Boton_f157ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_f157ActionPerformed
        // TODO add your handling code here:
         if(Campo_Anio.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Debe indicar el año", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
        
          anio_reporte=Integer.parseInt(Campo_Anio.getText());
       
        switch(Combo_Meses.getSelectedIndex())
        {
            case 0:mes_reporte=1;
                break;
            case 1:mes_reporte=2;
                break;
            case 2:mes_reporte=3;
                break;
            case 3:mes_reporte=4;
                break;
            case 4:mes_reporte=5;
                break;
            case 5:mes_reporte=6;
                break;
            case 6:mes_reporte=7;
                break;
            case 7:mes_reporte=8;
                break;
            case 8:mes_reporte=9;
                break;
            case 9:mes_reporte=10;
                break;
            case 10:mes_reporte=11;
                break;
            case 11:mes_reporte=12;
                break;
               
                
        }
        
       /*
        GenerarExistGeneral progress=new GenerarExistGeneral();
        Progreso.setVisible(true);
        progress.setFechaReporte(mes_reporte, anio_reporte);
        progress.setProgreso(Progreso);//paso la barra como parametro a la ventana de SwingWorker para que la actualice
        //progress.setSeccion(seccion);
        progress.execute();*/
       
       ConexionDatosdeReporte datosReporte=new ConexionDatosdeReporte();
       datosReporte.limpiar();
       datosReporte.setAnio(anio_reporte);
       datosReporte.setMesInicio(1);
       datosReporte.setMesFin(mes_reporte);
       datosReporte.setSeccion(seccion);
       datosReporte.guardar();
       
       ReporteF157 reporte=new ReporteF157();
       reporte.llamarReporte();
      
      
        }//else
    }//GEN-LAST:event_Boton_f157ActionPerformed

    private void boton_kardexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_kardexActionPerformed
        // TODO add your handling code here:
        
        Kardex_Articulos kardex=new Kardex_Articulos(null, true);
        kardex.setResizable(false);
        kardex.setLocationRelativeTo(null);
        kardex.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        kardex.setVisible(true);
    }//GEN-LAST:event_boton_kardexActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Reportes dialog = new Reportes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_Modelo4;
    private javax.swing.JButton Boton_f157;
    private javax.swing.JTextField Campo_Anio;
    private javax.swing.JComboBox Combo_Meses;
    private javax.swing.JLabel Etiq_encabezado;
    private javax.swing.JPanel Panel_Layout;
    private javax.swing.JPanel Panel_barra;
    private javax.swing.JPanel Panel_general;
    public javax.swing.JProgressBar Progreso;
    private javax.swing.JButton boton_kardex;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel panel1;
    // End of variables declaration//GEN-END:variables
}
